import Image from "next/image";

const morning = ["교과·예체능 방과후", "공동교육과정", "메타인지반"];
const afternoon = ["비교과 프로그램", "공동교육과정", "학년별 메타인지반"];
const courses = [["소프트웨어와 생활", "2학년", "09:00~12:30"], ["국제관계와 국제기구", "2학년", "13:30~17:20"], ["세계문제와 미래사회", "1학년", "09:00~12:30"]];
const activities = [["희소가치(인문 철학) 아카데미", "1·2학년", "오후 운영"], ["생태탐사 프로젝트", "1·2학년", "오후 운영"], ["인문사회주제탐구 프로젝트", "1학년", "오후 운영"], ["수리과학주제탐구 프로젝트", "1학년", "오후 운영"]];
const faqs = [
  ["윈터스쿨은 언제 운영되며 누가 참여할 수 있나요?", "2027년 1월 4일(월)부터 1월 15일(금)까지 총 10일간 운영합니다. 대상은 1·2학년 희망 학생이며 3학년은 제외합니다."],
  ["신청은 언제, 어디에서 하나요?", "실제 수능대비 교과 방과후, 메타인지반 신청은 11월 중 리로스쿨을 통해 진행합니다. 프로그램 최종 확정 후, 신청일자를 공지합니다."],
  ["기숙사생도 희망자만 참여하나요?", "기숙사생은 오전 학교 프로그램에 반드시 참여해야 합니다. 오후 운영은 신청한 프로그램과 자기주도학습 참여 여부에 따라 달라집니다."],
  ["하교 시간은 모두 같은가요?", "등교 시간은 같지만 하교 시간은 신청한 프로그램과 오후 자기주도학습 참여 여부에 따라 달라질 수 있습니다."],
  ["급식은 어떻게 신청하나요?", "급식은 10일 전체 신청 또는 전체 미신청만 가능합니다."],
  ["공동교육과정과 비교과 프로그램을 중복 신청할 수 있나요?", "공동교육과정 수강생은 담당 교사의 허락을 받은 경우 비교과 프로그램에 참여할 수도 있습니다."],
];

function Arrow() {
  return <svg viewBox="0 0 24 24" aria-hidden="true" className="size-5 fill-none stroke-current stroke-2"><path d="M5 12h14M13 6l6 6-6 6" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

function Heading({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) {
  return <div className="mb-10 max-w-3xl md:mb-12"><p className="eyebrow">{eyebrow}</p><h2 className="section-title">{title}</h2><p className="mt-4 text-base leading-8 text-slate-600 dark:text-slate-300">{children}</p></div>;
}

function ProgramPanel({ kind, title, items, warm = false }: { kind: string; title: string; items: string[][]; warm?: boolean }) {
  return <article className={`overflow-hidden rounded-3xl border bg-white shadow-sm dark:bg-slate-900 ${warm ? "border-orange-200 dark:border-orange-900" : "border-violet-200 dark:border-violet-900"}`}>
    <header className={`flex items-start justify-between p-6 md:p-8 ${warm ? "bg-orange-50 dark:bg-orange-950/40" : "bg-violet-50 dark:bg-violet-950/40"}`}><div><p className={`text-sm font-black tracking-widest ${warm ? "text-orange-700 dark:text-orange-300" : "text-violet-700 dark:text-violet-300"}`}>{kind}</p><h3 className="mt-1 text-3xl font-black tracking-tight text-slate-900 dark:text-white">{title}</h3></div><span className="rounded-full bg-white px-3 py-1 text-sm font-black text-violet-700 shadow-sm dark:bg-slate-800 dark:text-violet-300">{items.length}개 {title === "공동교육과정" ? "확정" : "확보"}</span></header>
    <ul>{items.map(([name, grade, schedule], index) => <li key={name} className="flex gap-4 border-t border-slate-100 px-6 py-5 dark:border-slate-800 md:px-8"><span className="text-sm font-black text-slate-400">{String(index + 1).padStart(2, "0")}</span><div><b className="block text-lg text-slate-900 dark:text-white">{name}</b><small className="mt-1 block text-base text-slate-500 dark:text-slate-400">{grade} · {schedule}</small></div></li>)}</ul>
  </article>;
}

function Period({ title, time, lessons, tracks, afternoon = false }: { title: string; time: string; lessons: string; tracks: string[]; afternoon?: boolean }) {
  return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-lg shadow-slate-900/5 dark:border-slate-800 dark:bg-slate-900 sm:p-7"><div className="flex flex-col items-start justify-between gap-3 sm:flex-row sm:items-center"><span className={`rounded-lg px-4 py-1.5 font-black ${afternoon ? "bg-orange-100 text-orange-700 dark:bg-orange-950 dark:text-orange-300" : "bg-violet-100 text-violet-700 dark:bg-violet-950 dark:text-violet-300"}`}>{title}</span><b className="text-slate-900 dark:text-white">{time}</b></div><p className="my-5 rounded-lg bg-slate-100 px-3 py-2 text-center text-xs text-slate-500 dark:bg-slate-800 dark:text-slate-400">{lessons}</p><ul className="space-y-2.5">{tracks.map((track, i) => <li key={track} className={`flex gap-3 rounded-xl px-4 py-3 font-extrabold ${i === 0 && afternoon ? "bg-orange-50 text-orange-700 dark:bg-orange-950/50 dark:text-orange-300" : i === 0 ? "bg-violet-50 text-violet-700 dark:bg-violet-950/50 dark:text-violet-300" : i === 1 ? "bg-teal-50 text-teal-700 dark:bg-teal-950/50 dark:text-teal-300" : "bg-violet-50 text-violet-700 dark:bg-violet-950/50 dark:text-violet-300"}`}><span className="text-xs opacity-60">0{i + 1}</span>{track}</li>)}</ul></article>;
}

export default function Home() {
  return <main>
    <header className="sticky top-0 z-50 flex h-[72px] items-center justify-between border-b border-slate-200/80 bg-white/90 px-5 backdrop-blur-xl dark:border-slate-800 dark:bg-slate-950/90 xl:px-[max(24px,calc((100vw-1180px)/2))]"><a href="#top" className="flex items-center gap-3" aria-label="광양고 윈터스쿨 홈"><span className="grid size-10 place-items-center rounded-xl bg-slate-900 font-black text-white dark:bg-violet-600">GY</span><span><b className="block text-sm leading-tight text-slate-900 dark:text-white">광양고등학교</b><small className="block text-[10px] font-black tracking-widest text-violet-600">WINTER SCHOOL</small></span></a><nav aria-label="주요 메뉴" className="hidden gap-8 text-sm font-bold text-slate-600 dark:text-slate-300 md:flex"><a href="#schedule">운영 형태</a><a href="#programs">개설 프로그램</a><a href="#apply">신청 안내</a><a href="#faq">자주 묻는 질문</a></nav></header>

    <section id="top" className="shell grid min-h-[650px] items-center gap-12 py-16 lg:grid-cols-[1.15fr_.85fr] lg:gap-20 lg:py-24"><div><span className="inline-flex items-center gap-2 rounded-full border border-violet-200 bg-violet-50 px-3 py-1.5 text-xs font-black text-violet-700 dark:border-violet-900 dark:bg-violet-950 dark:text-violet-300"><i className="size-2 rounded-full bg-violet-600 ring-4 ring-violet-100 dark:ring-violet-900" />윈터스쿨 사전안내</span><p className="eyebrow mt-8">2026학년도 광양고등학교</p><h1 className="text-[3.25rem] leading-[1.06] font-black tracking-[-.065em] text-slate-950 sm:text-7xl lg:text-[5.2rem] dark:text-white">겨울방학 중<br /><span className="text-violet-600">프로그램 안내</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-slate-600 sm:text-lg dark:text-slate-300">학생마다 다른 요구사항을 하나로 담은 몰입형 프로그램 <strong className="font-extrabold text-slate-800 dark:text-slate-100">(수능 대비 교과 방과후, 공동교육과정, 메타인지반, 비교과 프로그램)</strong></p><div className="mt-9 flex flex-col items-start gap-5 sm:flex-row sm:items-center sm:gap-8"><a className="inline-flex items-center gap-3 rounded-xl bg-slate-950 px-5 py-3.5 font-extrabold text-white shadow-xl shadow-slate-900/15 transition hover:-translate-y-0.5 hover:bg-violet-600 dark:bg-violet-600" href="#apply">신청 안내 확인 <Arrow /></a><a className="font-extrabold text-violet-600" href="#schedule">하루 일과 보기 ↓</a></div></div>
      <aside className="relative overflow-hidden rounded-[28px] border border-slate-200 bg-gradient-to-br from-white to-violet-50 p-7 shadow-2xl shadow-violet-950/10 dark:border-slate-700 dark:from-slate-900 dark:to-slate-950 sm:p-9" aria-label="윈터스쿨 핵심 일정"><div className="flex justify-between text-xs font-black text-slate-500"><span>운영 기간</span><b className="tracking-widest text-violet-600">10 DAYS</b></div><strong className="mt-8 block text-2xl leading-tight font-black tracking-[-.04em] text-slate-950 sm:text-3xl dark:text-white">1월 4일(월) <span className="text-slate-300">-</span> 1월 15일(금)</strong><p className="mt-3 text-slate-500 dark:text-slate-400">2027년 · 월요일부터 금요일</p><dl className="mt-7 border-t border-slate-200 text-sm dark:border-slate-700">{[["대상", "1·2학년 희망 학생"], ["리로스쿨 사전 수요조사", "11.21(토) 09:00"], ["신청 방법", "리로스쿨 학생 직접 신청"]].map(([dt, dd]) => <div key={dt} className="flex justify-between gap-4 border-b border-slate-200 py-3.5 dark:border-slate-700"><dt className="text-slate-500">{dt}</dt><dd className="text-right font-extrabold text-slate-900 dark:text-white">{dd}</dd></div>)}</dl></aside></section>

    <section className="shell py-14 sm:py-20" aria-label="윈터스쿨 시그니처 메시지">
      <div className="relative flex min-h-[440px] overflow-hidden rounded-[32px] bg-[#180708] shadow-2xl shadow-orange-950/30 sm:min-h-[380px]">
        <Image src="/2026-09-29-winter-school-fire-signature.png" alt="강렬하게 타오르는 불꽃 배경" fill className="object-cover" sizes="(max-width: 768px) 100vw, 1180px" />
        <div className="absolute inset-0 bg-gradient-to-b from-black/25 via-black/10 to-black/75" />
        <div className="relative z-10 flex w-full flex-col items-center justify-center px-6 py-14 text-center text-white sm:px-12">
          <p className="text-sm font-black tracking-[.18em] text-orange-300 sm:text-base">광양고등학교 자공고2.0 윈터스쿨</p>
          <h2 className="mt-5 text-4xl leading-tight font-black tracking-[-.055em] drop-shadow-[0_4px_18px_rgba(0,0,0,.85)] sm:text-6xl">
            나의 겨울은<br /><span className="text-amber-300">여름보다 뜨거워야 한다</span>
          </h2>
          <p className="mt-7 text-lg font-bold text-white/90 drop-shadow-lg sm:text-2xl">겨울방학에도 광양고는 쉬지않고 달린다.</p>
        </div>
      </div>
    </section>

    <section id="schedule" className="shell section-space"><Heading eyebrow="DAILY FLOW" title="Time Table">오전 집중 수업, 점심시간, 오후 선택 프로그램으로 이어집니다. 신청 내용에 따라 하교 시간은 달라질 수 있습니다.</Heading><div className="grid gap-5 lg:grid-cols-[1fr_150px_1fr]"><Period title="오전" time="09:00 - 12:30" lessons="1교시 09:00-10:40 · 2교시 10:50-12:30" tracks={morning} /><div className="flex items-center justify-center gap-4 rounded-3xl border border-dashed border-slate-300 bg-violet-50 p-6 text-center lg:flex-col dark:border-slate-700 dark:bg-slate-900"><span className="text-base font-black text-slate-600 dark:text-slate-300">점심시간</span><strong className="text-2xl leading-tight font-black text-slate-900 dark:text-white">12:30<br className="hidden lg:block" /> - 13:30</strong><small className="text-base font-bold text-violet-600">급식 · 휴식</small></div><Period title="오후" time="13:30 - 17:00" lessons="1교시 13:30-15:10 · 2교시 15:20-17:00" tracks={afternoon} afternoon /></div><figure className="mt-9 rounded-3xl border border-slate-200 bg-white p-2 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-4"><Image src="/2026-09-29-winter-school-summary.png" width={1536} height={1024} alt="2026학년도 윈터스쿨 운영 기간과 운영 취지를 설명한 안내 이미지" className="h-auto w-full rounded-2xl" sizes="(max-width: 768px) 100vw, 1100px" priority /><figcaption className="px-2 pt-3 pb-1 text-center text-xs text-slate-500">교육력제고부 확정 운영안 요약 자료</figcaption></figure></section>

    <section id="programs" className="section-space bg-slate-50 dark:bg-slate-950"><div className="shell"><Heading eyebrow="PROGRAMS" title="프로그램 안내(추가예정)">현재 확정된 과정을 먼저 안내합니다. 교과·예체능 방과후와 메타인지반은 학생 수요조사 결과를 반영해 추가됩니다.</Heading><div className="grid gap-5 lg:grid-cols-2"><ProgramPanel kind="정규 연계" title="공동교육과정" items={courses} /><ProgramPanel kind="탐구·체험" title="비교과 프로그램" items={activities} warm /></div><div className="mt-5 flex min-h-[150px] flex-col items-start gap-6 rounded-2xl bg-gradient-to-r from-violet-600 via-violet-600 to-fuchsia-500 p-8 text-white shadow-xl shadow-violet-600/20 ring-1 ring-white/20 sm:flex-row sm:items-center sm:p-10"><span className="shrink-0 rounded-xl bg-white/20 px-4 py-2 text-base font-black text-white shadow-sm ring-1 ring-white/30 backdrop-blur-sm">추후 안내</span><div><b className="text-xl font-black text-white">교과·예체능 방과후 · 메타인지반</b><p className="mt-1 text-base text-white/90">학생 사전 수요조사 결과를 반영해 개설 과목과 반을 확정합니다.</p></div></div></div></section>

    <section id="apply" className="shell section-space"><Heading eyebrow="HOW TO APPLY" title="수능 대비 교과방과후 개설을 위한 사전 조사 확인 필수"><span className="text-lg">신청은 리로스쿨에서 학생이 직접 진행합니다. 별도의 외부 신청 링크는 없습니다.</span></Heading><div className="grid overflow-hidden rounded-3xl bg-violet-600 text-white shadow-2xl shadow-violet-600/20 md:grid-cols-[1.5fr_.75fr]"><div className="p-7 sm:p-9"><span className="text-sm font-black tracking-widest text-violet-200">신청 시작</span><strong className="mt-2 block text-4xl font-black tracking-tight sm:text-5xl">2026. 11. 21. 토요일</strong><b className="mt-2 block text-lg text-violet-100">오전 9시부터 · 인원 마감 시까지</b></div><div className="bg-slate-950 p-7 sm:p-9"><span className="text-sm font-black tracking-widest text-slate-400">신청 방법</span><strong className="mt-2 block text-4xl font-black">리로스쿨</strong><p className="mt-1 text-lg text-slate-300">학생 계정으로 직접 신청</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["01", "대상 학년", "1·2학년 희망 학생이 대상이며 3학년은 제외합니다."], ["02", "기숙사생", "오전 학교 프로그램은 선택이 아닌 필수 참여입니다."], ["03", "급식 신청", "10일 전체 식사 또는 전체 미신청만 가능합니다."], ["04", "중복 참여", "공동교육과정 수강생은 담당 교사의 허락 후 비교과 프로그램에 참여할 수도 있습니다."]].map(([n, t, d]) => <article key={n} className={`rounded-2xl border p-7 ${n === "02" ? "border-violet-400 bg-violet-50 shadow-lg shadow-violet-100 dark:border-violet-700 dark:bg-violet-950/50 dark:shadow-none" : n === "03" ? "border-orange-400 bg-orange-50 shadow-lg shadow-orange-100 dark:border-orange-700 dark:bg-orange-950/50 dark:shadow-none" : "border-slate-200 dark:border-slate-800"}`}><span className={`text-sm font-black ${n === "03" ? "text-orange-600" : "text-violet-600"}`}>{n}</span><h3 className={`mt-4 text-xl font-black ${n === "02" ? "text-violet-800 dark:text-violet-200" : n === "03" ? "text-orange-800 dark:text-orange-200" : "text-slate-900 dark:text-white"}`}>{t}</h3><p className="mt-2 text-base leading-7 text-slate-600 dark:text-slate-300">{d}</p></article>)}</div></section>

    <section id="faq" className="section-space bg-slate-950 text-white"><div className="shell grid gap-8 lg:grid-cols-[.7fr_1.3fr] lg:gap-20"><Heading eyebrow="Q&A" title="자주 묻는 질문">학생과 학부모님이 가장 궁금해할 내용을 먼저 정리했습니다.</Heading><div>{faqs.map(([q, a], i) => <details key={q} open={i === 0} className="group border-t border-white/15 last:border-b"><summary className="grid cursor-pointer list-none grid-cols-[30px_1fr_20px] items-center gap-3 py-5 font-bold marker:hidden"><span className="text-xs font-black text-violet-400">{String(i + 1).padStart(2, "0")}</span>{q}<i className="text-xl not-italic text-slate-500 transition group-open:rotate-45">+</i></summary><p className="mr-4 mb-6 ml-[42px] leading-7 text-slate-400">{a}</p></details>)}</div></div></section>
    <footer className="border-t border-slate-800 bg-[#160d2a] py-9 text-white"><div className="shell flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><b className="block">광양고등학교</b><span className="text-xs text-slate-500">2026학년도 WINTER SCHOOL</span></div><p className="text-sm text-slate-400">문의 · 교육력제고부</p></div></footer>
  </main>;
}
